server:
  port: 9090
mybatis:
  type-aliases-package: com.zjw.appspringbootmybatis.pojo
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/edu?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456

  redis:
    host: localhost
    password:
    port: 6379
  jackson:
    time-zone: GMT+8

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

permission:
  teacher:
    apply: all
    class: list-teacherId
  admin:
    admin: all
    apply: all
    build: all
    classroom: all
    class: all
    config: all
    course: all
    dept: all
    major: all
    schedule: all
    section: all
    selection: all
    student: all
    teacher: all
  student:

